"""Add AI accessibility module tables

Revision ID: 146d8e6de5e9
Revises: eaf8eb7e39d3
Create Date: 2026-07-30 00:38:49.366498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146d8e6de5e9'
down_revision: Union[str, Sequence[str], None] = 'eaf8eb7e39d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('admin_override', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_descriptions_image_hash'), 'diagram_descriptions', ['image_hash'], unique=True)
    op.create_table('formula_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formula_hash', sa.String(length=64), nullable=False),
    sa.Column('spoken_explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_caches_formula_hash'), 'formula_caches', ['formula_hash'], unique=True)
    op.create_table('ocr_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_caches_image_hash'), 'ocr_caches', ['image_hash'], unique=True)
    op.create_table('tts_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('audio_base64', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('voice_gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_caches_text_hash'), 'tts_caches', ['text_hash'], unique=True)
    op.create_table('voice_command_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_key', sa.String(length=100), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_command_aliases_alias_text'), 'voice_command_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_voice_command_aliases_command_key'), 'voice_command_aliases', ['command_key'], unique=False)
    op.create_table('accessibility_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=True),
    sa.Column('voice_gender', sa.String(length=20), nullable=True),
    sa.Column('voice_speed', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('voice_pitch', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('high_contrast_mode', sa.Boolean(), nullable=True),
    sa.Column('large_font_mode', sa.Boolean(), nullable=True),
    sa.Column('keyboard_navigation', sa.Boolean(), nullable=True),
    sa.Column('auto_read_question', sa.Boolean(), nullable=True),
    sa.Column('auto_read_options', sa.Boolean(), nullable=True),
    sa.Column('auto_read_instructions', sa.Boolean(), nullable=True),
    sa.Column('voice_confirmation', sa.Boolean(), nullable=True),
    sa.Column('speech_recognition', sa.Boolean(), nullable=True),
    sa.Column('screen_reader_optimization', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_settings_student_id'), 'accessibility_settings', ['student_id'], unique=True)
    op.create_table('speech_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_transcript', sa.Text(), nullable=True),
    sa.Column('detected_command', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_logs_user_id'), 'speech_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speech_logs_user_id'), table_name='speech_logs')
    op.drop_table('speech_logs')
    op.drop_index(op.f('ix_accessibility_settings_student_id'), table_name='accessibility_settings')
    op.drop_table('accessibility_settings')
    op.drop_index(op.f('ix_voice_command_aliases_command_key'), table_name='voice_command_aliases')
    op.drop_index(op.f('ix_voice_command_aliases_alias_text'), table_name='voice_command_aliases')
    op.drop_table('voice_command_aliases')
    op.drop_index(op.f('ix_tts_caches_text_hash'), table_name='tts_caches')
    op.drop_table('tts_caches')
    op.drop_index(op.f('ix_ocr_caches_image_hash'), table_name='ocr_caches')
    op.drop_table('ocr_caches')
    op.drop_index(op.f('ix_formula_caches_formula_hash'), table_name='formula_caches')
    op.drop_table('formula_caches')
    op.drop_index(op.f('ix_diagram_descriptions_image_hash'), table_name='diagram_descriptions')
    op.drop_table('diagram_descriptions')
    # ### end Alembic commands ###
