apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-frontend
  labels:
    app: aegis-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aegis-frontend
  template:
    metadata:
      labels:
        app: aegis-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontendRepository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: aegis-frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: aegis-frontend
